### ISSUE TITLE
没有页面，好期待下一步做出来的效果

### ISSUE THREAD

**Issue by renoblog** [roverliang/butterfly#1]

**Comment by roverliang** [comment]
这个测试很简单。
1、进入Core 文件夹。执行 node ./jobList.js 。会依次爬取数据。
等shell 不再继续输出后。
然后ctrl + C 终端当前进程。

2、在Core 文件夹内执行jobList.js 。方法同上。

目前存在的bug：不能一次性抓取，循环嵌套http请求会hung up。至今没有找到问题所在。

希望能够共同学习。
