### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by renoblog** [roverliang/butterfly#2]
app.js 数据库这块应该这样写，不然会报错
var Db = require('mongodb').Db;
Server = require('mongodb').Server;
var db = new Db('mongotest', new Server('localhost', 27017));
db.open(function(err, db) {
    if(err) throw error;
    var collection = db.collection('user');
    collection.find(function(error,cursor){
        cursor.each(function(error,doc){
            if(doc){
                console.log("name:"+doc.name+" age:"+doc.age);
            }
        });
    });
});

**Comment by roverliang** [comment]
好的。谢谢了。最近刚换工作，比较忙。等忙完后会继续开发这个爬虫。星期天抽空我会仔细跑下代码的。

**Comment by renoblog** [comment]
我是新手，刚接触MEAN技术栈，请多多指教，共同学习

**Comment by renoblog** [comment]
请问这个项目还在维护吗，怎么没有更新？

**Comment by roverliang** [comment]
抱歉啊。刚入职新公司，事情较多，你加我qq：859869103吧。我也是nodeJs新手，共同学习。

2016-05-05 19:08 GMT+08:00 Reno <notifications@github.com>:
